export enum Role {
  COMPLIANCE_OWNER = "COMPLIANCE_OWNER",
  DEPARTMENT_OWNER = "DEPARTMENT_OWNER",
  CONTROL_OWNER = "CONTROL_OWNER",
  EXECUTIVE_VIEWER = "EXECUTIVE_VIEWER",
  AUDITOR = "AUDITOR",
}